# Generated by Django 4.2.2 on 2025-09-07 14:22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_blog_body_alter_blog_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='blog body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='short description'),
        ),
    ]
