# Generated by Django 5.1.2 on 2025-02-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallinks_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_heading',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='platform',
            field=models.CharField(max_length=26),
        ),
    ]
