# Generated by Django 5.1.2 on 2025-02-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_about_about_heading_alter_sociallinks_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_heading',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='platform',
            field=models.CharField(max_length=25),
        ),
    ]
